---

- name: Install Odoo dependencies
  apt:  pkg={{ item }}
        state=present
        update_cache={{ odoo_apt_update_cache }}
        cache_valid_time={{ odoo_apt_cache_valid_time }}
  with_items: "{{ odoo_debian_packages }}"
  tags:
    - odoo_packages
  when: ansible_distribution != 'Archlinux'

- name: Install Odoo dependencies in Archlinux
  yay:
        name={{ item }}
        update_cache={{ odoo_pacman_update_cache }}
  with_items: "{{ odoo_arch_packages }}"
  tags:
    - odoo_packages
  when: ansible_distribution == 'Archlinux'

- name: Install Odoo dependencies (PyPi)
  pip: name={{ item }}
  with_items: "{{ odoo_pypi_packages }}"
  tags:
    - odoo_packages

- import_tasks: config.yml
  tags:
    - odoo_config
